name: Chatflows

on:
  push:
    branches: [ development_chatflow_test ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Gathering deps
        run: |
          sudo apt-get update
          sudo apt-get install -y git python3-pip python3-venv python3-setuptools cron
          sudo pip3 install poetry
          sudo poetry run pip3 install pytest pytest-cov
      - name: Install
        run: |
          sudo poetry install
      - name: Run tests
        run: |
          sudo poetry run pytest -sv tests/clients/explorer/test_models.py  --cov=jumpscale --cov-report=xml
      - name: Upload coverage to Codecov
        if: success()
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          